### ISSUE TITLE
Hi,Your project can transalte .frag file to llvm's .bc file??

### ISSUE THREAD

**Issue by SakuraXiaMF** [Lycheus/GLSL-LLVM#1]
Hi,Your project can transalte .frag file to llvm's .bc file??
I am very interest for your project,but i don't see how to translate GLES file to LLVM IR?
Your project brief tell me ,this is a compiler based on LLVM,but how to use LLVM in it ?

**Comment by Lycheus** [comment]
Hi, this is a compiler of a novel GPU ISA built for a national science project. The compiler itself is built based on LLVM and what the compiler does is to take OpenGL ES GLSL (the shading language) as input and compile into LLVM IR with vector instruction support. The backend of the LLVM  is targeting to our novel GPU ISA, but it can be changed to other targets if you want. So, the short answer for your question is, no, not exactly. The compile pass is not designed to compile fragment/vertex shader to .bc file and executed, but pass into the LLVM backend to our GPU ISA. It is still possible to reuse most of our frontend and generate a usable bytecode (.bc) if this is what you want. Cheers. Kenny
